### ISSUE TITLE
MainSlide in DOM hierarchy

### ISSUE THREAD

**Issue by jpyne17** [jpyne17/biosynthage#13]
Having some positioning issues with the nav after deciding **not** to use viewports for the height (as fixed nav heights seem to be the industry standard, with good aesthetic reason).

Given that MainSlide is a container that takes up the entire viewport, and we want the a constant instance of the Menu component (nav), doesn't this mean we need could do with having MainSlide at the top of the DOM hierarchy in App.js, with Menu as its child?

Also thought this would be useful for any fancy transitions between site background between pages that could be effected by state change.

Let us know!

**Comment by Usefulmaths** [comment]
We certainly can do that, but there may be a couple of issues. The first one being that if we ever want opacity in MainSlide, or maybe even other properties, there is a chance Menu will automatically inherit these. Secondly, when using 'cinema', the Menu will **also** be covered. Not sure whether we want that. 

If we're using fixed height, wouldn't the navigation buttons on the Menu look a little bit strange when we have a device that has a larger height than its width? I reckon it would be useful to figure out how to do basic condition with CSS depending on screen size.

**Comment by jpyne17** [comment]
So I have noticed on every site I've been on the last few days that the nav rarely scales with the viewport. Often the nav contents will adjust positioning responsively, or change a single button for mobile sizes, but no scaling of height occurs.

In response to your two issues:
Opacity Inheritance - my research seems to imply that the common escape for this in CSS3 is to use RGBA for colouring properties rather than the opacity property. Everyone seem to find the opacity attribute very annoying.
Cinema - looking at Bennie's code, surely we just could create a blank class called '.cinema' that we assign to the nav and the video. Bennie's JS code works by calling .cinema() on a regular jQuery selector. Calling it on '.cinema' should therefore not cover the menu, that is if the menu has a higher zindex than the background.

Thoughts champ?

**Comment by Usefulmaths** [comment]
In that case, we could just fix the heights and let it scale with viewport width only. I think that'd look pretty good. 

Hmm, when setting up the origin skeleton of the site I experimented with the RGBA and still found we had the same problem? We can definitely test it out again. 

Right, he's using a method that just changes the attributes of some jQuery selector -- in this case the video. That's basically what we have but not compiled into one nice method. Did you try setting up the .cinema() with the video, exactly like Bennie's?

**Comment by jpyne17** [comment]
DOM hierarchy rejigged with the new routing... closing this bad boy.
