### ISSUE TITLE
slimline-nav: Video + billBoardDiv doesn't span general screen dimensions.

### ISSUE THREAD

**Issue by Usefulmaths** [jpyne17/biosynthage#15]
This is probably because billBoardDiv height is given in pixels. Also, there are a few other attributes I see that are set in pixels. It would be good if you could change these to viewport dimensions or % :).

http://ctrlv.in/809165

**Comment by jpyne17** [comment]
Okay so upon consultation with a few people yesterday I decided to dump the 'cinema' effect and keep it just in an oblong black translucent div that the video sits in.

As an aside on that video of theirs I put in, the thumbnail is poor so will get them to amend that, and also as I've said before, I might replace it with the Vimeo player as I much prefer it.
