### ISSUE TITLE
slimline-nav: Colour animation + Video fade.

### ISSUE THREAD

**Issue by Usefulmaths** [jpyne17/biosynthage#16]
I REALLY like what you've done here, really good job. Although, do you think it may look a bit better to have the fade to colour happen as you load the page and have the video fade in as you click the button? I find having both the fade to colour and fade to video in one sequence of animations is a bit long. Thoughts?

**Comment by jpyne17** [comment]
I can do that fairly quickly for us to have a look at, also I can do one where the colour change and div fade simultaneously transition.

Once I've finished off LandingPage for good I'll create a branch where I can commit a few tweaks like that ready for checkout.

**Comment by jpyne17** [comment]
Implemented this!
