### ISSUE TITLE
ImageArray 'non-unique key prop' warning

### ISSUE THREAD

**Issue by jpyne17** [jpyne17/biosynthage#22]
Debugger console (upon routing to DescriptionPage):
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of ImageArray.  See https://fb.me/react-warning-keys for more information.`
`    in ImageBlock (created by ImageArray)`
`    in ImageArray (created by DescriptionPage)`
`    in div (created by DescriptionPage)`
`    in div (created by DescriptionPage)`
`    in div (created by DescriptionPage)`
`    in DescriptionPage (created by RouterContext)`

Any ideas Liam?

**Comment by Usefulmaths** [comment]
When a component is the **_owner_** of multiple components, the **_ownee_** components must have a unique 'key' attribute. This ensures that the identity and state of the components are maintained upon re-rendering.

**Comment by jpyne17** [comment]
nice one champy
